# Generated by Django 3.1.13 on 2021-08-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_auto_20210802_1653'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phone',
            new_name='Client',
        ),
    ]
