# Generated by Django 3.1.13 on 2021-09-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0003_registration_registrationinvitecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationinvitecode',
            name='invite_code',
            field=models.CharField(default='15^tuyr=hje(', max_length=12),
        ),
    ]
