# Generated by Django 3.1.13 on 2021-08-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0003_auto_20210813_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_of',
            field=models.CharField(default='N8Brown', max_length=100),
            preserve_default=False,
        ),
    ]
