# Generated by Django 3.1.13 on 2021-09-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0004_auto_20210907_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationinvitecode',
            name='invite_code',
            field=models.CharField(default='25zw6+*=i7k2', max_length=12),
        ),
    ]
