# Generated by Django 3.1.13 on 2021-08-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('phone', 'client_of')},
        ),
    ]
