# Generated by Django 3.1.13 on 2021-09-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0005_auto_20210907_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationinvitecode',
            name='invite_code',
            field=models.CharField(max_length=12),
        ),
    ]
