# Generated by Django 3.1.13 on 2021-09-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0006_auto_20210907_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationinvitecode',
            name='invite_code',
            field=models.CharField(default='81wl8bfn6fi8', max_length=12, unique=True),
        ),
    ]
