# Generated by Django 3.1.13 on 2021-09-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0007_auto_20210907_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationinvitecode',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registrationinvitecode',
            name='invite_code',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
