# Generated by Django 3.1.13 on 2021-09-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0008_auto_20210914_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationinvitecode',
            options={'verbose_name_plural': 'Registration Invite Codes'},
        ),
        migrations.AddField(
            model_name='registrationinvitecode',
            name='redeemed_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
