# Generated by Django 3.1.13 on 2021-09-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0009_auto_20210914_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclient',
            name='last_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userclient',
            name='last_reply',
            field=models.DateField(blank=True, null=True),
        ),
    ]
