# Generated by Django 3.1.13 on 2021-09-17 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0011_auto_20210917_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclient',
            name='signed_up',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
