# Generated by Django 3.1.13 on 2021-09-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0012_auto_20210917_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='message_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='message_frequency',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='message_limit',
            field=models.IntegerField(default=1000),
        ),
    ]
