# Generated by Django 3.1.13 on 2021-09-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0013_auto_20210917_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
